from tkinter import *
from PIL import ImageTk,Image
from tkinter import ttk
from tkinter import messagebox
import mysql.connector
import random
from time import strftime
from datetime import date, datetime
from priceAndProcurment import PriceProcurment
from veza import Konekcija

class Restaurant:
    def __init__(self,root):
        self.root=root
        self.root.title("Restaurant")
        self.root.geometry("1850x1050+0+0")

        self.root.protocol('WM_DELETE_WINDOW',self.closeWindow)

        self.var_quantity1=IntVar()
        self.var_quantity2=IntVar()
        self.var_quantity3=IntVar()
        self.var_quantity4=IntVar()
        self.var_quantity5=IntVar()
        self.var_quantity6=IntVar()
        self.var_quantity7=IntVar()
        self.var_quantity8=IntVar()
        self.var_quantity9=IntVar()
        self.var_quantity10=IntVar()
        self.var_quantity11=IntVar()
        self.var_quantity12=IntVar()
        self.var_quantity13=IntVar()
        self.var_quantity14=IntVar()
        self.var_quantity15=IntVar()
        self.var_quantity16=IntVar()
        self.var_quantity17=IntVar()
        self.var_quantity18=IntVar()
        self.var_quantity19=IntVar()
        self.var_quantity20=IntVar()
        self.var_quantity21=IntVar()
        self.var_quantity22=IntVar()
        self.var_quantity23=IntVar()
        self.var_quantity24=IntVar()
        self.var_quantity25=IntVar()
        self.var_quantity26=IntVar()
        self.var_espresso=StringVar()
        self.var_espresso.set("Espresso")
        self.var_aqua=StringVar()
        self.var_aqua.set("Aqua Viva")
        self.var_knjaz=StringVar()
        self.var_knjaz.set("Knjaz Miloš")
        self.var_coca=StringVar()
        self.var_coca.set("Coca Cola")
        self.var_next=StringVar()
        self.var_next.set("Next")
        self.var_limunada=StringVar()
        self.var_limunada.set("Limunada")
        self.var_cedjena=StringVar()
        self.var_cedjena.set("Cedjena Narandža")
        self.var_redbull=StringVar()
        self.var_redbull.set("Red Bull")
        self.var_kozel=StringVar()
        self.var_kozel.set("Kozel")
        self.var_vino=StringVar()
        self.var_vino.set("Crveno Vino")
        self.var_whisky=StringVar()
        self.var_whisky.set("Whisky")
        self.var_cognac=StringVar()
        self.var_cognac.set("Cognac")
        self.var_martini=StringVar()
        self.var_martini.set("Martini")
        self.var_omlet=StringVar()
        self.var_omlet.set("Omlet")
        self.var_pomfrit=StringVar()
        self.var_pomfrit.set("Pomfrit")
        self.var_meze=StringVar()
        self.var_meze.set("Meze")
        self.var_sendvič=StringVar()
        self.var_sendvič.set("Klub Sendvič")
        self.var_čorba=StringVar()
        self.var_čorba.set("Teleća Čorba")
        self.var_paradajz=StringVar()
        self.var_paradajz.set("Paradajz Salata")
        self.var_krastavac=StringVar()
        self.var_krastavac.set("Krastavac Svež")
        self.var_pečurke=StringVar()
        self.var_pečurke.set("Pečurke na žaru")
        self.var_špagete=StringVar()
        self.var_špagete.set("Špagete")
        self.var_bečka=StringVar()
        self.var_bečka.set("Bečka Šnicla")
        self.var_medaljoni=StringVar()
        self.var_medaljoni.set("Svinjski Medaljoni")
        self.var_pastrmka=StringVar()
        self.var_pastrmka.set("Sveža Pastrmka")
        self.var_tuna=StringVar()
        self.var_tuna.set("Tuna")
        self.var_price1=IntVar()
        self.var_price2=IntVar()
        self.var_price3=IntVar()
        self.var_price4=IntVar()
        self.var_price5=IntVar()
        self.var_price6=IntVar()
        self.var_price7=IntVar()
        self.var_price8=IntVar()
        self.var_price9=IntVar()
        self.var_price10=IntVar()
        self.var_price11=IntVar()
        self.var_price12=IntVar()
        self.var_price13=IntVar()
        self.var_price14=IntVar()
        self.var_price15=IntVar()
        self.var_price16=IntVar()
        self.var_price17=IntVar()
        self.var_price18=IntVar()
        self.var_price19=IntVar()
        self.var_price20=IntVar()
        self.var_price21=IntVar()
        self.var_price22=IntVar()
        self.var_price23=IntVar()
        self.var_price24=IntVar()
        self.var_price25=IntVar()
        self.var_price26=IntVar()
        self.var_idA1=IntVar()
        self.var_idA2=IntVar()
        self.var_idA3=IntVar()
        self.var_idA4=IntVar()
        self.var_idA5=IntVar()
        self.var_idA6=IntVar()
        self.var_idA7=IntVar()
        self.var_idA8=IntVar()
        self.var_idA9=IntVar()
        self.var_idA10=IntVar()
        self.var_idA11=IntVar()
        self.var_idA12=IntVar()
        self.var_idA13=IntVar()
        self.var_idA14=IntVar()
        self.var_idA15=IntVar()
        self.var_idA16=IntVar()
        self.var_idA17=IntVar()
        self.var_idA18=IntVar()
        self.var_idA19=IntVar()
        self.var_idA20=IntVar()
        self.var_idA21=IntVar()
        self.var_idA22=IntVar()
        self.var_idA23=IntVar()
        self.var_idA24=IntVar()
        self.var_idA25=IntVar()
        self.var_idA26=IntVar()
        self.var_KN1=IntVar()
        self.var_KN2=IntVar()
        self.var_KN3=IntVar()
        self.var_KN4=IntVar()
        self.var_KN5=IntVar()
        self.var_KN6=IntVar()
        self.var_KN7=IntVar()
        self.var_KN8=IntVar()
        self.var_KN9=IntVar()
        self.var_KN10=IntVar()
        self.var_KN11=IntVar()
        self.var_KN12=IntVar()
        self.var_KN13=IntVar()
        self.var_KN14=IntVar()
        self.var_KN15=IntVar()
        self.var_KN16=IntVar()
        self.var_KN17=IntVar()
        self.var_KN18=IntVar()
        self.var_KN19=IntVar()
        self.var_KN20=IntVar()
        self.var_KN21=IntVar()
        self.var_KN22=IntVar()
        self.var_KN23=IntVar()
        self.var_KN24=IntVar()
        self.var_KN25=IntVar()
        self.var_KN26=IntVar()

        self.var_searchBy=StringVar()
        self.var_searchText=StringVar()

        self.var_billNo=IntVar()
        self.var_idguest=IntVar()
        self.var_condition=IntVar()
        self.var_total=IntVar()
        self.var_statusR=StringVar()
        self.var_statusR.set("otvoren")
        self.var_billDay=IntVar()

        self.var_Day=IntVar()
        self.var_profit=IntVar()
        self.var_statusD=StringVar()
        

        self.var_idnorms=IntVar()
        self.var_nameArticle=StringVar()
        self.var_priceArticle=IntVar()
        self.var_quantityArticle=IntVar()
        self.var_idArticle=IntVar()

        self.var_tour=IntVar()


        img1=Image.open(r"restaurantsPhoto/restoran5.jpg")
        img1=img1.resize((620,140),Image.ANTIALIAS)
        self.photoimg1=ImageTk.PhotoImage(img1)

        lblImage=Label(self.root,image=self.photoimg1,bd=4,relief=RIDGE)
        lblImage.place(x=0,y=0,width=620,height=140)

        img2=Image.open(r"restaurantsPhoto/restoran2.jpg")
        img2=img2.resize((620,140),Image.ANTIALIAS)
        self.photoimg2=ImageTk.PhotoImage(img2)

        lblImage2=Label(self.root,image=self.photoimg2,bd=4,relief=RIDGE)
        lblImage2.place(x=620,y=0,width=620,height=140)

        img3=Image.open(r"restaurantsPhoto/restoran1.jpg")
        img3=img3.resize((610,140),Image.ANTIALIAS)
        self.photoimg3=ImageTk.PhotoImage(img3)

        lblImage3=Label(self.root,image=self.photoimg3,bd=4,relief=RIDGE)
        lblImage3.place(x=1240,y=0,width=610,height=140)

        titleLbl=Label(self.root,text="Restaurant system and charge",font=("times new roman",40,"bold"),bg="black",fg="gold",bd=4,relief=RIDGE)
        titleLbl.place(x=0,y=140,width=1850,height=70)

        self.lbl = Label(self.root, font = ('calibri', 15, 'bold'),
        foreground = 'gold',background="black")
        self.lbl.place(x=10,y=160,width=300)
        self.date()


        frameArticles=Frame(self.root,bg="black",bd=4,relief=RIDGE)
        frameArticles.place(x=0,y=210,width=920,height=800)

        img4=Image.open(r"drinksPhoto/espresso.jpg")
        img4=img4.resize((100,50),Image.ANTIALIAS)
        self.photoimg4=ImageTk.PhotoImage(img4)
        l1=Label(frameArticles,image=self.photoimg4)
        l1.place(x=10,y=10,width=100,height=50)
        signingup1=ttk.Entry(frameArticles,textvariable=self.var_quantity1)
        signingup1.place(x=120,y=30,width=50,height=30)
        signingupC=ttk.Entry(frameArticles,textvariable=self.var_espresso)
        signingupC.place(x=180,y=30,width=100,height=30)
        Signingup1=ttk.Entry(frameArticles,textvariable=self.var_price1)
        Signingup1.place(x=290,y=30,width=70,height=30)
        id1=ttk.Entry(frameArticles,textvariable=self.var_idA1)
        id1.place(x=370,y=30,width=30,height=30)
        kN1=ttk.Entry(frameArticles,textvariable=self.var_KN1)
        kN1.place(x=390,y=30,width=50,height=30)

        img5=Image.open(r"drinksPhoto/aqua viva.jpg")
        img5=img5.resize((100,50),Image.ANTIALIAS)
        self.photoimg5=ImageTk.PhotoImage(img5)
        l2=Label(frameArticles,image=self.photoimg5)
        l2.place(x=10,y=70,width=100,height=50)
        signingup2=ttk.Entry(frameArticles,textvariable=self.var_quantity2)
        signingup2.place(x=120,y=90,width=50,height=30)
        signingupR=ttk.Entry(frameArticles,textvariable=self.var_aqua)
        signingupR.place(x=180,y=90,width=100,height=30)
        Signingup2=ttk.Entry(frameArticles,textvariable=self.var_price2)
        Signingup2.place(x=290,y=90,width=70,height=30)
        id2=ttk.Entry(frameArticles,textvariable=self.var_idA2)
        id2.place(x=370,y=90,width=30,height=30)
        kN2=ttk.Entry(frameArticles,textvariable=self.var_KN2)
        kN2.place(x=390,y=90,width=50,height=30)

        img6=Image.open(r"drinksPhoto/knjaz.jpg")
        img6=img6.resize((100,50),Image.ANTIALIAS)
        self.photoimg6=ImageTk.PhotoImage(img6)
        l3=Label(frameArticles,image=self.photoimg6)
        l3.place(x=10,y=130,width=100,height=50)
        signingup3=ttk.Entry(frameArticles,textvariable=self.var_quantity3)
        signingup3.place(x=120,y=150,width=50,height=30)
        signingupK=ttk.Entry(frameArticles,textvariable=self.var_knjaz)
        signingupK.place(x=180,y=150,width=100,height=30)
        Signingup3=ttk.Entry(frameArticles,textvariable=self.var_price3)
        Signingup3.place(x=290,y=150,width=70,height=30)
        id3=ttk.Entry(frameArticles,textvariable=self.var_idA3)
        id3.place(x=370,y=150,width=30,height=30)
        kN3=ttk.Entry(frameArticles,textvariable=self.var_KN3)
        kN3.place(x=390,y=150,width=50,height=30)

        img7=Image.open(r"drinksPhoto/coke.png")
        img7=img7.resize((100,50),Image.ANTIALIAS)
        self.photoimg7=ImageTk.PhotoImage(img7)
        l4=Label(frameArticles,image=self.photoimg7)
        l4.place(x=10,y=190,width=100,height=50)
        signingup4=ttk.Entry(frameArticles,textvariable=self.var_quantity4)
        signingup4.place(x=120,y=210,width=50,height=30)
        signingupC=ttk.Entry(frameArticles,textvariable=self.var_coca)
        signingupC.place(x=180,y=210,width=100,height=30)
        Signingup4=ttk.Entry(frameArticles,textvariable=self.var_price4)
        Signingup4.place(x=290,y=210,width=70,height=30)
        id4=ttk.Entry(frameArticles,textvariable=self.var_idA4)
        id4.place(x=370,y=210,width=30,height=30)
        kN4=ttk.Entry(frameArticles,textvariable=self.var_KN4)
        kN4.place(x=390,y=210,width=50,height=30)

        img8=Image.open(r"drinksPhoto/next.jpg")
        img8=img8.resize((100,50),Image.ANTIALIAS)
        self.photoimg8=ImageTk.PhotoImage(img8)
        l5=Label(frameArticles,image=self.photoimg8)
        l5.place(x=10,y=250,width=100,height=50)
        signingup5=ttk.Entry(frameArticles,textvariable=self.var_quantity5)
        signingup5.place(x=120,y=270,width=50,height=30)
        signingupR=ttk.Entry(frameArticles,textvariable=self.var_next)
        signingupR.place(x=180,y=270,width=100,height=30)
        Signingup5=ttk.Entry(frameArticles,textvariable=self.var_price5)
        Signingup5.place(x=290,y=270,width=70,height=30)
        id5=ttk.Entry(frameArticles,textvariable=self.var_idA5)
        id5.place(x=370,y=270,width=30,height=30)
        kN5=ttk.Entry(frameArticles,textvariable=self.var_KN5)
        kN5.place(x=390,y=270,width=50,height=30)

        img9=Image.open(r"drinksPhoto/limunada.jpg")
        img9=img9.resize((100,50),Image.ANTIALIAS)
        self.photoimg9=ImageTk.PhotoImage(img9)
        l6=Label(frameArticles,image=self.photoimg9)
        l6.place(x=10,y=310,width=100,height=50)
        signingup6=ttk.Entry(frameArticles,textvariable=self.var_quantity6)
        signingup6.place(x=120,y=330,width=50,height=30)
        signingupK=ttk.Entry(frameArticles,textvariable=self.var_limunada)
        signingupK.place(x=180,y=330,width=100,height=30)
        Signingup6=ttk.Entry(frameArticles,textvariable=self.var_price6)
        Signingup6.place(x=290,y=330,width=70,height=30)
        id6=ttk.Entry(frameArticles,textvariable=self.var_idA6)
        id6.place(x=370,y=330,width=30,height=30)
        kN6=ttk.Entry(frameArticles,textvariable=self.var_KN6)
        kN6.place(x=390,y=330,width=50,height=30)

        img10=Image.open(r"drinksPhoto/cedjena.jpeg")
        img10=img10.resize((100,50),Image.ANTIALIAS)
        self.photoimg10=ImageTk.PhotoImage(img10)
        l7=Label(frameArticles,image=self.photoimg10)
        l7.place(x=10,y=370,width=100,height=50)
        signingup7=ttk.Entry(frameArticles,textvariable=self.var_quantity7)
        signingup7.place(x=120,y=390,width=50,height=30)
        signingupC=ttk.Entry(frameArticles,textvariable=self.var_cedjena)
        signingupC.place(x=180,y=390,width=100,height=30)
        Signingup7=ttk.Entry(frameArticles,textvariable=self.var_price7)
        Signingup7.place(x=290,y=390,width=70,height=30)
        id7=ttk.Entry(frameArticles,textvariable=self.var_idA7)
        id7.place(x=370,y=390,width=30,height=30)
        kN7=ttk.Entry(frameArticles,textvariable=self.var_KN7)
        kN7.place(x=390,y=390,width=50,height=30)

        img11=Image.open(r"drinksPhoto/redbull.jpg")
        img11=img11.resize((100,50),Image.ANTIALIAS)
        self.photoimg11=ImageTk.PhotoImage(img11)
        l8=Label(frameArticles,image=self.photoimg11)
        l8.place(x=10,y=430,width=100,height=50)
        signingup8=ttk.Entry(frameArticles,textvariable=self.var_quantity8)
        signingup8.place(x=120,y=450,width=50,height=30)
        signingupR=ttk.Entry(frameArticles,textvariable=self.var_redbull)
        signingupR.place(x=180,y=450,width=100,height=30)
        Signingup8=ttk.Entry(frameArticles,textvariable=self.var_price8)
        Signingup8.place(x=290,y=450,width=70,height=30)
        id8=ttk.Entry(frameArticles,textvariable=self.var_idA8)
        id8.place(x=370,y=450,width=30,height=30)
        kN8=ttk.Entry(frameArticles,textvariable=self.var_KN8)
        kN8.place(x=390,y=450,width=50,height=30)

        img12=Image.open(r"drinksPhoto/kozel.png")
        img12=img12.resize((100,50),Image.ANTIALIAS)
        self.photoimg12=ImageTk.PhotoImage(img12)
        l9=Label(frameArticles,image=self.photoimg12)
        l9.place(x=10,y=490,width=100,height=50)
        signingup9=ttk.Entry(frameArticles,textvariable=self.var_quantity9)
        signingup9.place(x=120,y=510,width=50,height=30)
        signingupK=ttk.Entry(frameArticles,textvariable=self.var_kozel)
        signingupK.place(x=180,y=510,width=100,height=30)
        Signingup9=ttk.Entry(frameArticles,textvariable=self.var_price9)
        Signingup9.place(x=290,y=510,width=70,height=30)
        id9=ttk.Entry(frameArticles,textvariable=self.var_idA9)
        id9.place(x=370,y=510,width=30,height=30)
        kN9=ttk.Entry(frameArticles,textvariable=self.var_KN9)
        kN9.place(x=390,y=510,width=50,height=30)

        img13=Image.open(r"drinksPhoto/vino.png")
        img13=img13.resize((100,50),Image.ANTIALIAS)
        self.photoimg13=ImageTk.PhotoImage(img13)
        l10=Label(frameArticles,image=self.photoimg13)
        l10.place(x=10,y=550,width=100,height=50)
        signingup10=ttk.Entry(frameArticles,textvariable=self.var_quantity10)
        signingup10.place(x=120,y=570,width=50,height=30)
        signingupC=ttk.Entry(frameArticles,textvariable=self.var_vino)
        signingupC.place(x=180,y=570,width=100,height=30)
        Signingup10=ttk.Entry(frameArticles,textvariable=self.var_price10)
        Signingup10.place(x=290,y=570,width=70,height=30)
        id10=ttk.Entry(frameArticles,textvariable=self.var_idA10)
        id10.place(x=370,y=570,width=30,height=30)
        kN10=ttk.Entry(frameArticles,textvariable=self.var_KN10)
        kN10.place(x=390,y=570,width=50,height=30)

        img14=Image.open(r"drinksPhoto/whisky.jpg")
        img14=img14.resize((100,50),Image.ANTIALIAS)
        self.photoimg14=ImageTk.PhotoImage(img14)
        l11=Label(frameArticles,image=self.photoimg14)
        l11.place(x=10,y=610,width=100,height=50)
        signingup11=ttk.Entry(frameArticles,textvariable=self.var_quantity11)
        signingup11.place(x=120,y=630,width=50,height=30)
        signingupR=ttk.Entry(frameArticles,textvariable=self.var_whisky)
        signingupR.place(x=180,y=630,width=100,height=30)
        Signingup11=ttk.Entry(frameArticles,textvariable=self.var_price11)
        Signingup11.place(x=290,y=630,width=70,height=30)
        id11=ttk.Entry(frameArticles,textvariable=self.var_idA11)
        id11.place(x=370,y=630,width=30,height=30)
        kN11=ttk.Entry(frameArticles,textvariable=self.var_KN11)
        kN11.place(x=390,y=630,width=50,height=30)

        img15=Image.open(r"drinksPhoto/cognac.jpg")
        img15=img15.resize((100,50),Image.ANTIALIAS)
        self.photoimg15=ImageTk.PhotoImage(img15)
        l12=Label(frameArticles,image=self.photoimg15)
        l12.place(x=10,y=670,width=100,height=50)
        signingup12=ttk.Entry(frameArticles,textvariable=self.var_quantity12)
        signingup12.place(x=120,y=690,width=50,height=30)
        signingupK=ttk.Entry(frameArticles,textvariable=self.var_cognac)
        signingupK.place(x=180,y=690,width=100,height=30)
        Signingup12=ttk.Entry(frameArticles,textvariable=self.var_price12)
        Signingup12.place(x=290,y=690,width=70,height=30)
        id12=ttk.Entry(frameArticles,textvariable=self.var_idA12)
        id12.place(x=370,y=690,width=30,height=30)
        kN12=ttk.Entry(frameArticles,textvariable=self.var_KN12)
        kN12.place(x=390,y=690,width=50,height=30)

        img16=Image.open(r"drinksPhoto/martini.jpeg")
        img16=img16.resize((100,50),Image.ANTIALIAS)
        self.photoimg16=ImageTk.PhotoImage(img16)
        l13=Label(frameArticles,image=self.photoimg16)
        l13.place(x=10,y=730,width=100,height=50)
        signingup13=ttk.Entry(frameArticles,textvariable=self.var_quantity13)
        signingup13.place(x=120,y=750,width=50,height=30)
        signingupK=ttk.Entry(frameArticles,textvariable=self.var_martini)
        signingupK.place(x=180,y=750,width=100,height=30)
        Signingup13=ttk.Entry(frameArticles,textvariable=self.var_price13)
        Signingup13.place(x=290,y=750,width=70,height=30)
        id13=ttk.Entry(frameArticles,textvariable=self.var_idA13)
        id13.place(x=370,y=750,width=30,height=30)
        kN13=ttk.Entry(frameArticles,textvariable=self.var_KN13)
        kN13.place(x=390,y=750,width=50,height=30)

### new line 

        img17=Image.open(r"foodPhoto/omlet.jpg")
        img17=img17.resize((100,50),Image.ANTIALIAS)
        self.photoimg17=ImageTk.PhotoImage(img17)
        l14=Label(frameArticles,image=self.photoimg17)
        l14.place(x=460,y=10,width=100,height=50)
        signingup14=ttk.Entry(frameArticles,textvariable=self.var_quantity14)
        signingup14.place(x=570,y=30,width=50,height=30)
        signingupC=ttk.Entry(frameArticles,textvariable=self.var_omlet)
        signingupC.place(x=630,y=30,width=100,height=30)
        Signingup14=ttk.Entry(frameArticles,textvariable=self.var_price14)
        Signingup14.place(x=740,y=30,width=70,height=30)
        id14=ttk.Entry(frameArticles,textvariable=self.var_idA14)
        id14.place(x=820,y=30,width=30,height=30)
        kN14=ttk.Entry(frameArticles,textvariable=self.var_KN14)
        kN14.place(x=840,y=30,width=50,height=30)

        img18=Image.open(r"foodPhoto/pomfrit.jpg")
        img18=img18.resize((100,50),Image.ANTIALIAS)
        self.photoimg18=ImageTk.PhotoImage(img18)
        l15=Label(frameArticles,image=self.photoimg18)
        l15.place(x=460,y=70,width=100,height=50)
        signingup15=ttk.Entry(frameArticles,textvariable=self.var_quantity15)
        signingup15.place(x=570,y=90,width=50,height=30)
        signingupR=ttk.Entry(frameArticles,textvariable=self.var_pomfrit)
        signingupR.place(x=630,y=90,width=100,height=30)
        Signingup15=ttk.Entry(frameArticles,textvariable=self.var_price15)
        Signingup15.place(x=740,y=90,width=70,height=30)
        id15=ttk.Entry(frameArticles,textvariable=self.var_idA15)
        id15.place(x=820,y=90,width=30,height=30)
        kN15=ttk.Entry(frameArticles,textvariable=self.var_KN15)
        kN15.place(x=840,y=90,width=50,height=30)

        img19=Image.open(r"foodPhoto/meze.jpg")
        img19=img19.resize((100,50),Image.ANTIALIAS)
        self.photoimg19=ImageTk.PhotoImage(img19)
        l16=Label(frameArticles,image=self.photoimg19)
        l16.place(x=460,y=130,width=100,height=50)
        signingup16=ttk.Entry(frameArticles,textvariable=self.var_quantity16)
        signingup16.place(x=570,y=150,width=50,height=30)
        signingupK=ttk.Entry(frameArticles,textvariable=self.var_meze)
        signingupK.place(x=630,y=150,width=100,height=30)
        Signingup16=ttk.Entry(frameArticles,textvariable=self.var_price16)
        Signingup16.place(x=740,y=150,width=70,height=30)
        id16=ttk.Entry(frameArticles,textvariable=self.var_idA16)
        id16.place(x=820,y=150,width=30,height=30)
        kN16=ttk.Entry(frameArticles,textvariable=self.var_KN16)
        kN16.place(x=840,y=150,width=50,height=30)

        img20=Image.open(r"foodPhoto/klubsendvič.jpg")
        img20=img20.resize((100,50),Image.ANTIALIAS)
        self.photoimg20=ImageTk.PhotoImage(img20)
        l17=Label(frameArticles,image=self.photoimg20)
        l17.place(x=460,y=190,width=100,height=50)
        signingup17=ttk.Entry(frameArticles,textvariable=self.var_quantity17)
        signingup17.place(x=570,y=210,width=50,height=30)
        signingupC=ttk.Entry(frameArticles,textvariable=self.var_sendvič)
        signingupC.place(x=630,y=210,width=100,height=30)
        Signingup17=ttk.Entry(frameArticles,textvariable=self.var_price17)
        Signingup17.place(x=740,y=210,width=70,height=30)
        id17=ttk.Entry(frameArticles,textvariable=self.var_idA17)
        id17.place(x=820,y=210,width=30,height=30)
        kN17=ttk.Entry(frameArticles,textvariable=self.var_KN17)
        kN17.place(x=840,y=210,width=50,height=30)

        img21=Image.open(r"foodPhoto/čorba.jpg")
        img21=img21.resize((100,50),Image.ANTIALIAS)
        self.photoimg21=ImageTk.PhotoImage(img21)
        l18=Label(frameArticles,image=self.photoimg21)
        l18.place(x=460,y=250,width=100,height=50)
        signingup18=ttk.Entry(frameArticles,textvariable=self.var_quantity18)
        signingup18.place(x=570,y=270,width=50,height=30)
        signingupR=ttk.Entry(frameArticles,textvariable=self.var_čorba)
        signingupR.place(x=630,y=270,width=100,height=30)
        Signingup18=ttk.Entry(frameArticles,textvariable=self.var_price18)
        Signingup18.place(x=740,y=270,width=70,height=30)
        id18=ttk.Entry(frameArticles,textvariable=self.var_idA18)
        id18.place(x=820,y=270,width=70,height=30)
        kN18=ttk.Entry(frameArticles,textvariable=self.var_KN18)
        kN18.place(x=840,y=270,width=50,height=30)

        img22=Image.open(r"foodPhoto/paradajz.jpg")
        img22=img22.resize((100,50),Image.ANTIALIAS)
        self.photoimg22=ImageTk.PhotoImage(img22)
        l19=Label(frameArticles,image=self.photoimg22)
        l19.place(x=460,y=310,width=100,height=50)
        signingup19=ttk.Entry(frameArticles,textvariable=self.var_quantity19)
        signingup19.place(x=570,y=330,width=50,height=30)
        signingupK=ttk.Entry(frameArticles,textvariable=self.var_paradajz)
        signingupK.place(x=630,y=330,width=100,height=30)
        Signingup19=ttk.Entry(frameArticles,textvariable=self.var_price19)
        Signingup19.place(x=740,y=330,width=70,height=30)
        id19=ttk.Entry(frameArticles,textvariable=self.var_idA19)
        id19.place(x=820,y=330,width=30,height=30)
        kN19=ttk.Entry(frameArticles,textvariable=self.var_KN19)
        kN19.place(x=840,y=330,width=50,height=30)

        img23=Image.open(r"foodPhoto/krastavac.jpg")
        img23=img23.resize((100,50),Image.ANTIALIAS)
        self.photoimg23=ImageTk.PhotoImage(img23)
        l20=Label(frameArticles,image=self.photoimg23)
        l20.place(x=460,y=370,width=100,height=50)
        signingup20=ttk.Entry(frameArticles,textvariable=self.var_quantity20)
        signingup20.place(x=570,y=390,width=50,height=30)
        signingupC=ttk.Entry(frameArticles,textvariable=self.var_krastavac)
        signingupC.place(x=630,y=390,width=100,height=30)
        Signingup20=ttk.Entry(frameArticles,textvariable=self.var_price20)
        Signingup20.place(x=740,y=390,width=70,height=30)
        id20=ttk.Entry(frameArticles,textvariable=self.var_idA20)
        id20.place(x=820,y=390,width=30,height=30)
        kN20=ttk.Entry(frameArticles,textvariable=self.var_KN20)
        kN20.place(x=840,y=390,width=50,height=30)

        img24=Image.open(r"foodPhoto/pečurke.png")
        img24=img24.resize((100,50),Image.ANTIALIAS)
        self.photoimg24=ImageTk.PhotoImage(img24)
        l21=Label(frameArticles,image=self.photoimg24)
        l21.place(x=460,y=430,width=100,height=50)
        signingup21=ttk.Entry(frameArticles,textvariable=self.var_quantity21)
        signingup21.place(x=570,y=450,width=50,height=30)
        signingupR=ttk.Entry(frameArticles,textvariable=self.var_pečurke)
        signingupR.place(x=630,y=450,width=100,height=30)
        Signingup21=ttk.Entry(frameArticles,textvariable=self.var_price21)
        Signingup21.place(x=740,y=450,width=70,height=30)
        id21=ttk.Entry(frameArticles,textvariable=self.var_idA21)
        id21.place(x=820,y=450,width=30,height=30)
        kN21=ttk.Entry(frameArticles,textvariable=self.var_KN21)
        kN21.place(x=840,y=450,width=50,height=30)

        img25=Image.open(r"foodPhoto/špagete.jpg")
        img25=img25.resize((100,50),Image.ANTIALIAS)
        self.photoimg25=ImageTk.PhotoImage(img25)
        l22=Label(frameArticles,image=self.photoimg25)
        l22.place(x=460,y=490,width=100,height=50)
        signingup22=ttk.Entry(frameArticles,textvariable=self.var_quantity22)
        signingup22.place(x=570,y=510,width=50,height=30)
        signingupK=ttk.Entry(frameArticles,textvariable=self.var_špagete)
        signingupK.place(x=630,y=510,width=100,height=30)
        Signingup22=ttk.Entry(frameArticles,textvariable=self.var_price22)
        Signingup22.place(x=740,y=510,width=70,height=30)
        id22=ttk.Entry(frameArticles,textvariable=self.var_idA22)
        id22.place(x=820,y=510,width=30,height=30)
        kN22=ttk.Entry(frameArticles,textvariable=self.var_KN22)
        kN22.place(x=840,y=510,width=50,height=30)

        img26=Image.open(r"foodPhoto/bečka.jpeg")
        img26=img26.resize((100,50),Image.ANTIALIAS)
        self.photoimg26=ImageTk.PhotoImage(img26)
        l23=Label(frameArticles,image=self.photoimg26)
        l23.place(x=460,y=550,width=100,height=50)
        signingup23=ttk.Entry(frameArticles,textvariable=self.var_quantity23)
        signingup23.place(x=570,y=570,width=50,height=30)
        signingupC=ttk.Entry(frameArticles,textvariable=self.var_bečka)
        signingupC.place(x=630,y=570,width=100,height=30)
        Signingup23=ttk.Entry(frameArticles,textvariable=self.var_price23)
        Signingup23.place(x=740,y=570,width=70,height=30)
        id23=ttk.Entry(frameArticles,textvariable=self.var_idA23)
        id23.place(x=820,y=570,width=30,height=30)
        kN23=ttk.Entry(frameArticles,textvariable=self.var_KN23)
        kN23.place(x=840,y=570,width=50,height=30)

        img27=Image.open(r"foodPhoto/file.jpg")
        img27=img27.resize((100,50),Image.ANTIALIAS)
        self.photoimg27=ImageTk.PhotoImage(img27)
        l24=Label(frameArticles,image=self.photoimg27)
        l24.place(x=460,y=610,width=100,height=50)
        signingup24=ttk.Entry(frameArticles,textvariable=self.var_quantity24)
        signingup24.place(x=570,y=630,width=50,height=30)
        signingupR=ttk.Entry(frameArticles,textvariable=self.var_medaljoni)
        signingupR.place(x=630,y=630,width=100,height=30)
        signingup24=ttk.Entry(frameArticles,textvariable=self.var_price24)
        signingup24.place(x=740,y=630,width=70,height=30)
        id24=ttk.Entry(frameArticles,textvariable=self.var_idA24)
        id24.place(x=820,y=630,width=30,height=30)
        kN24=ttk.Entry(frameArticles,textvariable=self.var_KN24)
        kN24.place(x=840,y=630,width=50,height=30)

        img28=Image.open(r"foodPhoto/pastrmka.jpg")
        img28=img28.resize((100,50),Image.ANTIALIAS)
        self.photoimg28=ImageTk.PhotoImage(img28)
        l25=Label(frameArticles,image=self.photoimg28)
        l25.place(x=460,y=670,width=100,height=50)
        signingup25=ttk.Entry(frameArticles,textvariable=self.var_quantity25)
        signingup25.place(x=570,y=690,width=50,height=30)
        signingupK=ttk.Entry(frameArticles,textvariable=self.var_pastrmka)
        signingupK.place(x=630,y=690,width=100,height=30)
        Signingup25=ttk.Entry(frameArticles,textvariable=self.var_price25)
        Signingup25.place(x=740,y=690,width=70,height=30)
        id25=ttk.Entry(frameArticles,textvariable=self.var_idA25)
        id25.place(x=820,y=690,width=30,height=30)
        k25=ttk.Entry(frameArticles,textvariable=self.var_KN25)
        k25.place(x=840,y=690,width=50,height=30)

        img29=Image.open(r"foodPhoto/tuna.jpg")
        img29=img29.resize((100,50),Image.ANTIALIAS)
        self.photoimg29=ImageTk.PhotoImage(img29)
        l26=Label(frameArticles,image=self.photoimg29)
        l26.place(x=460,y=730,width=100,height=50)
        signingup26=ttk.Entry(frameArticles,textvariable=self.var_quantity26)
        signingup26.place(x=570,y=750,width=50,height=30)
        signingupK=ttk.Entry(frameArticles,textvariable=self.var_tuna)
        signingupK.place(x=630,y=750,width=100,height=30)
        Signingup26=ttk.Entry(frameArticles,textvariable=self.var_price26)
        Signingup26.place(x=740,y=750,width=70,height=30)
        id26=ttk.Entry(frameArticles,textvariable=self.var_idA26)
        id26.place(x=820,y=750,width=30,height=30)
        kN26=ttk.Entry(frameArticles,textvariable=self.var_KN26)
        kN26.place(x=840,y=750,width=50,height=30)


        frameBill=LabelFrame(self.root,bd=2,relief=RIDGE,text="Look and search bills",font=("times new roman",12,"bold"),padx=2)
        frameBill.place(x=930,y=210,width=540,height=300)

        searchCombo=ttk.Combobox(frameBill,textvariable=self.var_searchBy,font=("times new roman",12,"bold"),width=14,state="readonly")
        searchCombo['value']=("brojračuna","status")
        searchCombo.current()
        searchCombo.grid(row=0,column=1,padx=2)
   
        searchText=ttk.Entry(frameBill,textvariable=self.var_searchText, font=("times new roman",12,"bold"),width=14)
        searchText.grid(row=0,column=2,padx=2)

        btnsearch=Button(frameBill,text="Search",command=self.searchbill, font=("times new roman",12,"bold"),bg="black",fg="gold",width=7)
        btnsearch.grid(row=0,column=3,padx=1)

        btnShow=Button(frameBill,text="Show All",command=self.ShowAllBills, font=("times new roman",12,"bold"),bg="black",fg="gold",width=7)
        btnShow.grid(row=0,column=4,padx=1)

        detailsTable1 =Frame(frameBill,bg="purple")
        detailsTable1.place(x=0,y=50,width=530,height=230)

        scroll_x = Scrollbar(detailsTable1,orient=HORIZONTAL)
        scroll_y = Scrollbar(detailsTable1,orient=VERTICAL)
        self.print=ttk.Treeview(detailsTable1,columns=("billNo","idguest","currentcondition","total","status","billDay"),xscrollcommand=scroll_x.set,yscrollcommand=scroll_y.set)
        scroll_x.pack(side=BOTTOM,fill=X)
        scroll_y.pack(side=RIGHT,fill=Y)
        scroll_x.config(command=self.print.xview) 
        scroll_y.config(command=self.print.yview)
        self.print.heading("billNo",text="Bill Number")
        self.print.heading("idguest",text="ID Guest")
        self.print.heading("currentcondition",text="Current")
        self.print.heading("total",text="Total")
        self.print.heading("status",text="Status")
        self.print.heading("billDay",text="billDay")
        self.print['show']='headings' 
        self.print.column("billNo",width=100) 
        self.print.column("idguest",width=100)
        self.print.column("currentcondition",width=100)
        self.print.column("total",width=100)
        self.print.column("status",width=120)
        self.print.column("billDay",width=100)
        self.print.bind("<ButtonRelease-1>",self.get_data)
        self.print.pack(fill=BOTH,expand=1)

        frameprofit=LabelFrame(self.root,bd=2,relief=RIDGE,text="Look at bills and profit",font=("times new roman",12,"bold"),padx=2)
        frameprofit.place(x=1470,y=210,width=440,height=300)

        buttonopenDay=Button(frameprofit,text="Open Day",command=self.openDay, font=("arial",10,"bold"),bg="black",fg="gold",width=7)
        buttonopenDay.grid(row=0,column=4)

        buttoncloseDay=Button(frameprofit,text="Close Day",command=self.closeDay, font=("times new roman",10,"bold"),bg="black",fg="gold",width=7)
        buttoncloseDay.grid(row=1,column=4)

        buttonprofit=Button(frameprofit,text="Sign Up",command=self.signingupBill, font=("arial",10,"bold"),bg="black",fg="gold",width=7)
        buttonprofit.grid(row=2,column=4)

        buttonDays=Button(frameprofit,text="Days",command=self.ShowAllDays, font=("times new roman",10,"bold"),bg="black",fg="gold",width=7)
        buttonDays.grid(row=3,column=4)

        buttonToday=Button(frameprofit,text="Today",command=self.ShowToday, font=("times new roman",10,"bold"),bg="black",fg="gold",width=7)
        buttonToday.grid(row=4,column=4)


        billNoLbl=Label(frameprofit,text="Bill",font=("times new roman",12,"bold"),padx=2,pady=3,width=7)
        billNoLbl.grid(row=0,column=0)

        billNoEntry=ttk.Entry(frameprofit,textvariable=self.var_billNo, width=9,state="readonly")
        billNoEntry.grid(row=0,column=1)

        idguestLbl=Label(frameprofit,text="Guest ID",font=("times new roman",12,"bold"),padx=2,pady=3,width=7)
        idguestLbl.grid(row=1,column=0)

        idguestEntry=ttk.Entry(frameprofit,textvariable=self.var_idguest, width=9)
        idguestEntry.grid(row=1,column=1)

        conditionLbl=Label(frameprofit,text="Condition",font=("times new roman",12,"bold"),padx=2,pady=3,width=7)
        conditionLbl.grid(row=2,column=0)

        conditionEntry=ttk.Entry(frameprofit,textvariable=self.var_condition, width=9)
        conditionEntry.grid(row=2,column=1)

        totalLbl=Label(frameprofit,text="Total",font=("times new roman",12,"bold"),padx=2,pady=3,width=7)
        totalLbl.grid(row=3,column=0)

        totalEntry=ttk.Entry(frameprofit,textvariable=self.var_total, width=9)
        totalEntry.grid(row=3,column=1)

        statusLbl=Label(frameprofit,text="StatusR",font=("times new roman",12,"bold"),padx=2,pady=3,width=7)
        statusLbl.grid(row=4,column=0)

        statusEntry=ttk.Entry(frameprofit,textvariable=self.var_statusR, width=9)
        statusEntry.grid(row=4,column=1)

        billDayLbl=Label(frameprofit,text="BDay",font=("times new roman",12,"bold"),padx=2,pady=3,width=7)
        billDayLbl.grid(row=0,column=2)

        billDayEntry=ttk.Entry(frameprofit,textvariable=self.var_billDay, width=9)
        billDayEntry.grid(row=0,column=3)

        DayLbl=Label(frameprofit,text="Day",font=("times new roman",12,"bold"),padx=2,pady=3,width=7)
        DayLbl.grid(row=2,column=2)

        DayEntry=ttk.Entry(frameprofit,textvariable=self.var_Day, width=9)
        DayEntry.grid(row=2,column=3)

        profitLbl=Label(frameprofit,text="Profit", font=("times new roman",12,"bold"),padx=2,pady=3,width=7)
        profitLbl.grid(row=3,column=2)

        profitEntry=ttk.Entry(frameprofit,textvariable=self.var_profit, width=9)
        profitEntry.grid(row=3,column=3)

        statusLbl=Label(frameprofit,text="StatusD",font=("times new roman",12,"bold"),padx=2,pady=3,width=7)
        statusLbl.grid(row=4,column=2)

        statusEntry=ttk.Entry(frameprofit,textvariable=self.var_statusD, width=9)
        statusEntry.grid(row=4,column=3)

        detailsTable2=Frame(frameprofit)
        detailsTable2.place(x=0,y=150,width=370,height=130)

        scroll_x2 = Scrollbar(detailsTable2,orient=HORIZONTAL)
        scroll_y2 = Scrollbar(detailsTable2,orient=VERTICAL)
        self.print2=ttk.Treeview(detailsTable2,columns=("day","cashbox","status"),xscrollcommand=scroll_x2.set,yscrollcommand=scroll_y2.set)
        scroll_x2.pack(side=BOTTOM,fill=X)
        scroll_y2.pack(side=RIGHT,fill=Y)
        scroll_x2.config(command=self.print2.xview) 
        scroll_y2.config(command=self.print2.yview)
        self.print2.heading("day",text="Day")
        self.print2.heading("cashbox",text="Cashbox")
        self.print2.heading("status",text="Status")
        self.print2['show']='headings'  
        self.print2.column("day",width=100)
        self.print2.column("cashbox",width=100)
        self.print2.column("status",width=100)
        self.print2.bind("<ButtonRelease-1>",self.get_data2)
        self.print2.pack(fill=BOTH,expand=1)


        frameDrink=LabelFrame(self.root,bd=2,relief=RIDGE,text="Order overview and drink/food charge",font=("times new roman",12,"bold"),padx=2)
        frameDrink.place(x=930,y=510,width=540,height=500)

        buttonorder=Button(frameDrink,text="Order",command=self.order, font=("arial",12,"bold"),bg="black",fg="gold",width=8)
        buttonorder.grid(row=0,column=0,pady=5)

        buttonnewtour=Button(frameDrink,text="New tour",command=self.neworder, font=("arial",12,"bold"),bg="black",fg="gold",width=8)
        buttonnewtour.grid(row=0,column=1)

        buttoncharge=Button(frameDrink,text="Charge",command=self.charge, font=("arial",12,"bold"),bg="black",fg="gold",width=8)
        buttoncharge.grid(row=0,column=2)

        buttondelete=Button(frameDrink,text="Delete",command=self.deletebill, font=("arial",12,"bold"),bg="black",fg="gold",width=8)
        buttondelete.grid(row=1,column=0,padx=10)

        buttonreset=Button(frameDrink,text="Reset",command=self.reset, font=("arial",12,"bold"),bg="black",fg="gold",width=8)
        buttonreset.grid(row=1,column=1,padx=10)

        buttonDrink=Button(frameDrink,text="Drink/Food",command=self.ShowArticles, font=("arial",12,"bold"),bg="black",fg="gold",width=8)
        buttonDrink.grid(row=1,column=2,padx=10)

        buttonLimit=Button(frameDrink,text="Limit",command=self.itemreduction, font=("arial",12,"bold"),bg="black",fg="gold",width=8)
        buttonLimit.grid(row=1,column=3,padx=10)


        idnormsLbl=Label(frameDrink,text="ID Norms",font=("times new roman",12,"bold"),padx=2,pady=3,width=10)
        idnormsLbl.grid(row=2,column=0)

        idnormsEntry=ttk.Entry(frameDrink,textvariable=self.var_idnorms, width=9)
        idnormsEntry.grid(row=2,column=1)

        nameLbl=Label(frameDrink,text="Drink/Food",font=("times new roman",12,"bold"),padx=2,pady=3,width=10)
        nameLbl.grid(row=2,column=2)

        nameEntry=ttk.Entry(frameDrink,textvariable=self.var_nameArticle, width=14)
        nameEntry.grid(row=2,column=3)

        priceArticleLbl=Label(frameDrink,text="Price",font=("times new roman",12,"bold"),padx=2,pady=3,width=10)
        priceArticleLbl.grid(row=3,column=0)

        priceArticleEntry=ttk.Entry(frameDrink,textvariable=self.var_priceArticle, width=9)
        priceArticleEntry.grid(row=3,column=1)

        quantityArticleLbl=Label(frameDrink,text="Quantity",font=("times new roman",12,"bold"),padx=2,pady=3,width=10)
        quantityArticleLbl.grid(row=3,column=2)

        quantityArticleEntry=ttk.Entry(frameDrink,textvariable=self.var_quantityArticle, width=9)
        quantityArticleEntry.grid(row=3,column=3)

        idArticleLbl=Label(frameDrink,text="ID Article",font=("times new roman",12,"bold"),padx=2,pady=3,width=10)
        idArticleLbl.grid(row=4,column=0)

        idArticleEntry=ttk.Entry(frameDrink,textvariable=self.var_idArticle, width=9)
        idArticleEntry.grid(row=4,column=1)

        btntour=Button(frameDrink,text="Tour",command=self.tour, font=("arial",12,"bold"),bg="black",fg="gold",width=8)
        btntour.place(x=10,y=190,width=100,height=30)

        tourEntry=ttk.Entry(frameDrink,textvariable=self.var_tour)
        tourEntry.place(x=120,y=190,width=100,height=30)

        detailsTable3=Frame(frameDrink)
        detailsTable3.place(x=0,y=230,width=530,height=250)
        
        scroll_x3 = Scrollbar(detailsTable3,orient=HORIZONTAL)
        scroll_y3 = Scrollbar(detailsTable3,orient=VERTICAL)
        self.print3=ttk.Treeview(detailsTable3,columns=("idnorms","nameArticle","price","quantity","idArticles"),xscrollcommand=scroll_x3.set,yscrollcommand=scroll_y3.set)
        scroll_x3.pack(side=BOTTOM,fill=X)
        scroll_y3.pack(side=RIGHT,fill=Y)
        scroll_x3.config(command=self.print3.xview) 
        scroll_y3.config(command=self.print3.yview)
        self.print3.heading("idnorms",text="ID Norms")
        self.print3.heading("nameArticle",text="Name")
        self.print3.heading("price",text="Price")
        self.print3.heading("quantity",text="Quantity")
        self.print3.heading("idArticles",text="ID Article")
        self.print3['show']='headings' 
        self.print3.column("idnorms",width=100) 
        self.print3.column("nameArticle",width=100)
        self.print3.column("price",width=100)
        self.print3.column("quantity",width=100)
        self.print3.column("idArticles",width=100)
        self.print3.bind("<ButtonRelease-1>",self.get_data3)
        self.print3.pack(fill=BOTH,expand=1)


        buttonWindow=Button(frameDrink,text="Price and Procurement",command=self.priceProcurment, font=("arial",10,"bold"),bg="black",fg="gold",width=10)
        buttonWindow.place(x=360,y=190,width=170,height=30)


        buttonOff=Button(self.root,text="Conection Off",command=self.off, font=("arial",10,"bold"),bg="black",fg="gold",width=10)
        buttonOff.place(x=1720,y=985,width=130,height=30)


    def ShowAllBills(self):
        con=Konekcija.getInstance()
        cur=con.cursor()
        cur.execute("SELECT * FROM restoranNaplata")
        rows=cur.fetchall()
        if(len(rows)!=0):
            self.print.delete(*self.print.get_children())
            for row in rows:
                self.print.insert('',END,values=row)
                con.commit()


    def get_data(self,event):
        cursor_row = self.print.focus()
        contents = self.print.item(cursor_row)
        row = contents['values']

        self.var_billNo.set(row[0])
        self.var_idguest.set(row[1])
        self.var_condition.set(row[2])
        self.var_total.set(row[3])
        self.var_statusR.set(row[4])
        self.var_billDay.set(row[5])

    def searchbill(self):
        con=Konekcija.getInstance()
        cur=con.cursor()
        cur.execute("SELECT * FROM restoranNaplata WHERE "+str(self.var_searchBy.get())+" LIKE binary '%"+self.var_searchText.get()+"%'") 
        rows = cur.fetchall()
        if(len(rows)!=0):
            self.print.delete(*self.print.get_children())
            for i in rows: 
                self.print.insert('',END,values=i)
                con.commit()
        else:
            self.print.delete(*self.print.get_children()) 


    def ShowAllDays(self):
        con=Konekcija.getInstance()
        cur=con.cursor()
        cur.execute("SELECT * FROM pazar")
        rows=cur.fetchall()
        if(len(rows)!=0):
            self.print2.delete(*self.print2.get_children())
            for row in rows:
                self.print2.insert('',END,values=row)
                con.commit()

    def ShowToday(self):
        con=Konekcija.getInstance()
        cur=con.cursor()
        cur.execute("SELECT * FROM pazar WHERE status='otvoren'")
        rows=cur.fetchall()
        if(len(rows)!=0):
            self.print2.delete(*self.print2.get_children())
            for row in rows:
                self.print2.insert('',END,values=row)
                con.commit()
    
    def get_data2(self,event):
        cursor_row = self.print2.focus()
        contents = self.print2.item(cursor_row)
        row = contents['values']

        self.var_Day.set(row[0])
        self.var_profit.set(row[1])
        self.var_statusD.set(row[2])
        

    def openDay(self):
        self.reset()
        self.var_statusD.set("započni")
        if self.var_profit.get()!=0 or self.var_statusD.get()!="započni":
            messagebox.showerror("Error","Day is already open or finished!")
        else:
            self.var_statusD.set("otvoren")
            con=Konekcija.getInstance()
            cursor=con.cursor()
            cursor.execute("INSERT INTO pazar(kasa,status) VALUES(%s,%s)",(self.var_profit.get(),self.var_statusD.get(),))
            con.commit()
            messagebox.showinfo("Welcome","Day is opened successfully",parent=self.root)
            self.reset()
            self.ShowToday()
            

    def closeDay(self):
        if self.var_statusD.get()!="otvoren":
            messagebox.showerror("Error","Day is already finished")
        else:
            con=Konekcija.getInstance()
            cursor=con.cursor()
            cursor.execute("UPDATE pazar SET status='zatvoren' WHERE dan=%s",(self.var_Day.get(),))
            con.commit()
            messagebox.showinfo("Good Bye","Day is closed successfully",parent=self.root)
            self.reset()
            self.ShowAllDays()
            
    def ShowArticles(self):
        con=Konekcija.getInstance()
        cur=con.cursor()
        cur.execute("SELECT * FROM normativi")
        rows=cur.fetchall()
        if(len(rows)!=0):
            self.print3.delete(*self.print3.get_children())
            for row in rows:
                self.print3.insert('',END,values=row)
                con.commit()

    def get_data3(self,event):
        cursor_row = self.print3.focus()
        contents = self.print3.item(cursor_row)
        row = contents['values']
        if (f"{row[1]}")==(f"{self.var_espresso.get()}"):
            self.var_price1.set(self.var_price1.get()+row[2])
            self.var_quantity1.set(self.var_quantity1.get()+1)
            self.var_KN1.set(self.var_KN1.get()+row[3])
            self.var_idA1.set(row[4])
        elif (f"{row[1]}")==(f"{self.var_aqua.get()}"):
            self.var_price2.set(self.var_price2.get()+row[2])
            self.var_quantity2.set(self.var_quantity2.get()+1)
            self.var_KN2.set(self.var_KN2.get()+row[3])
            self.var_idA2.set(row[4])
        elif (f"{row[1]}")==(f"{self.var_knjaz.get()}"):
            self.var_price3.set(self.var_price3.get()+row[2])
            self.var_quantity3.set(self.var_quantity3.get()+1)
            self.var_KN3.set(self.var_KN3.get()+row[3])
            self.var_idA3.set(row[4])
        elif (f"{row[1]}")==(f"{self.var_coca.get()}"):
            self.var_price4.set(self.var_price4.get()+row[2])
            self.var_quantity4.set(self.var_quantity4.get()+1)
            self.var_KN4.set(self.var_KN4.get()+row[3])
            self.var_idA4.set(row[4])
        elif (f"{row[1]}")==(f"{self.var_next.get()}"):
            self.var_price5.set(self.var_price5.get()+row[2])
            self.var_quantity5.set(self.var_quantity5.get()+1)
            self.var_KN5.set(self.var_KN5.get()+row[3])
            self.var_idA5.set(row[4])
        elif (f"{row[1]}")==(f"{self.var_limunada.get()}"):
            self.var_price6.set(self.var_price6.get()+row[2])
            self.var_quantity6.set(self.var_quantity6.get()+1)
            self.var_KN6.set(self.var_KN6.get()+row[3])
            self.var_idA6.set(row[4])
        elif (f"{row[1]}")==(f"{self.var_cedjena.get()}"):
            self.var_price7.set(self.var_price7.get()+row[2])
            self.var_quantity7.set(self.var_quantity7.get()+1)
            self.var_KN7.set(self.var_KN7.get()+row[3])
            self.var_idA7.set(row[4])
        elif (f"{row[1]}")==(f"{self.var_redbull.get()}"):
            self.var_price8.set(self.var_price8.get()+row[2])
            self.var_quantity8.set(self.var_quantity8.get()+1)
            self.var_KN8.set(self.var_KN8.get()+row[3])
            self.var_idA8.set(row[4])
        elif (f"{row[1]}")==(f"{self.var_kozel.get()}"):
            self.var_price9.set(self.var_price9.get()+row[2])
            self.var_quantity9.set(self.var_quantity9.get()+1)
            self.var_KN9.set(self.var_KN9.get()+row[3])
            self.var_idA9.set(row[4])
        elif (f"{row[1]}")==(f"{self.var_vino.get()}"):
            self.var_price10.set(self.var_price10.get()+row[2])
            self.var_quantity10.set(self.var_quantity10.get()+1)
            self.var_KN10.set(self.var_KN10.get()+row[3])
            self.var_idA10.set(row[4])
        elif (f"{row[1]}")==(f"{self.var_whisky.get()}"):
            self.var_price11.set(self.var_price11.get()+row[2])
            self.var_quantity11.set(self.var_quantity11.get()+1)
            self.var_KN11.set(self.var_KN11.get()+row[3])
            self.var_idA11.set(row[4])
        elif (f"{row[1]}")==(f"{self.var_cognac.get()}"):
            self.var_price12.set(self.var_price12.get()+row[2])
            self.var_quantity12.set(self.var_quantity12.get()+1)
            self.var_KN12.set(self.var_KN12.get()+row[3])
            self.var_idA12.set(row[4])
        elif (f"{row[1]}")==(f"{self.var_martini.get()}"):
            self.var_price13.set(self.var_price13.get()+row[2])
            self.var_quantity13.set(self.var_quantity13.get()+1)
            self.var_KN13.set(self.var_KN13.get()+row[3])
            self.var_idA13.set(row[4])
        elif (f"{row[1]}")==(f"{self.var_omlet.get()}"):
            self.var_price14.set(self.var_price14.get()+row[2])
            self.var_quantity14.set(self.var_quantity14.get()+1)
            self.var_KN14.set(self.var_KN14.get()+row[3])
            self.var_idA14.set(row[4])
        elif (f"{row[1]}")==(f"{self.var_pomfrit.get()}"):
            self.var_price15.set(self.var_price15.get()+row[2])
            self.var_quantity15.set(self.var_quantity15.get()+1)
            self.var_KN15.set(self.var_KN15.get()+row[3])
            self.var_idA15.set(row[4])
        elif (f"{row[1]}")==(f"{self.var_meze.get()}"):
            self.var_price16.set(self.var_price16.get()+row[2])
            self.var_quantity16.set(self.var_quantity16.get()+1)
            self.var_KN16.set(self.var_KN16.get()+row[3])
            self.var_idA16.set(row[4])
        elif (f"{row[1]}")==(f"{self.var_sendvič.get()}"):
            self.var_price17.set(self.var_price17.get()+row[2])
            self.var_quantity17.set(self.var_quantity17.get()+1)
            self.var_KN17.set(self.var_KN17.get()+row[3])
            self.var_idA17.set(row[4])
        elif (f"{row[1]}")==(f"{self.var_čorba.get()}"):
            self.var_price18.set(self.var_price18.get()+row[2])
            self.var_quantity18.set(self.var_quantity18.get()+1)
            self.var_KN18.set(self.var_KN18.get()+row[3])
            self.var_idA18.set(row[4])
        elif (f"{row[1]}")==(f"{self.var_paradajz.get()}"):
            self.var_price19.set(self.var_price19.get()+row[2])
            self.var_quantity19.set(self.var_quantity19.get()+1)
            self.var_KN19.set(self.var_KN19.get()+row[3])
            self.var_idA19.set(row[4])
        elif (f"{row[1]}")==(f"{self.var_krastavac.get()}"):
            self.var_price20.set(self.var_price20.get()+row[2])
            self.var_quantity20.set(self.var_quantity20.get()+1)
            self.var_KN20.set(self.var_KN20.get()+row[3])
            self.var_idA20.set(row[4])
        elif (f"{row[1]}")==(f"{self.var_pečurke.get()}"):
            self.var_price21.set(self.var_price21.get()+row[2])
            self.var_quantity21.set(self.var_quantity21.get()+1)
            self.var_KN21.set(self.var_KN21.get()+row[3])
            self.var_idA21.set(row[4])
        elif (f"{row[1]}")==(f"{self.var_špagete.get()}"):
            self.var_price22.set(self.var_price22.get()+row[2])
            self.var_quantity22.set(self.var_quantity22.get()+1)
            self.var_KN22.set(self.var_KN22.get()+row[3])
            self.var_idA22.set(row[4])
        elif (f"{row[1]}")==(f"{self.var_bečka.get()}"):
            self.var_price23.set(self.var_price23.get()+row[2])
            self.var_quantity23.set(self.var_quantity23.get()+1)
            self.var_KN23.set(self.var_KN23.get()+row[3])
            self.var_idA23.set(row[4])
        elif (f"{row[1]}")==(f"{self.var_medaljoni.get()}"):
            self.var_price24.set(self.var_price24.get()+row[2])
            self.var_quantity24.set(self.var_quantity24.get()+1)
            self.var_KN24.set(self.var_KN24.get()+row[3])
            self.var_idA24.set(row[4])
        elif (f"{row[1]}")==(f"{self.var_pastrmka.get()}"):
            self.var_price25.set(self.var_price25.get()+row[2])
            self.var_quantity25.set(self.var_quantity25.get()+1)
            self.var_KN25.set(self.var_KN25.get()+row[3])
            self.var_idA25.set(row[4])
        elif (f"{row[1]}")==(f"{self.var_tuna.get()}"):
            self.var_price26.set(self.var_price26.get()+row[2])
            self.var_quantity26.set(self.var_quantity26.get()+1)
            self.var_KN26.set(self.var_KN26.get()+row[3])
            self.var_idA26.set(row[4])
        self.var_idnorms.set(row[0])
        self.var_nameArticle.set(row[1])
        self.var_priceArticle.set(row[2])
        self.var_quantityArticle.set(row[3])
        self.var_idArticle.set(row[4])


    def order(self):
        self.itemreduction()
        self.tour()
        self.var_condition.set(self.var_tour.get())
        if self.var_idguest.get()==0:
            messagebox.showerror("Error", "Enter Guest ID!", parent=self.root)
        elif self.var_statusD.get()!="otvoren":
            messagebox.showerror("Error", "Bill must be enter for today!", parent=self.root)
        else:
            con=Konekcija.getInstance()
            cursor=con.cursor()
            cursor.execute("INSERT INTO restoranNaplata(idgosti,trenutnostanje,total,status,dan) VALUES(%s,%s,%s,%s,%s)",(self.var_idguest.get(),self.var_condition.get(),self.var_total.get(),self.var_statusR.get(),self.var_Day.get()))
            con.commit()
            messagebox.showinfo("OK","Order success",parent=self.root)
            self.reset()
            self.ShowAllBills()
            self.limit()
        
    def tour(self):
        sve=self.var_price1.get()+self.var_price2.get()+self.var_price3.get()+self.var_price4.get()+self.var_price5.get()+self.var_price6.get()+self.var_price7.get()+self.var_price8.get()+self.var_price9.get()+self.var_price10.get()+self.var_price11.get()+self.var_price12.get()+self.var_price13.get()+self.var_price14.get()+self.var_price15.get()+self.var_price16.get()+self.var_price17.get()+self.var_price18.get()+self.var_price19.get()+self.var_price20.get()+self.var_price21.get()+self.var_price22.get()+self.var_price23.get()+self.var_price24.get()+self.var_price25.get()+self.var_price26.get()
        self.var_tour.set(sve)

    def neworder(self):
        self.itemreduction()
        self.tour()
        if self.var_idguest.get()==0:
            messagebox.showerror("Error", "Enter Guest ID!", parent=self.root)
        elif self.var_condition.get()==0 or self.var_statusR.get()!="otvoren" :
            messagebox.showerror("Error", "Bill does not exist or bill is charged already!", parent=self.root)
        elif self.var_statusD.get()!="otvoren":
                messagebox.showerror("Error", "Bill must be enter for today !", parent=self.root)
        else:
            self.var_condition.set(self.var_condition.get()+self.var_tour.get())
            try:
                con=Konekcija.getInstance()
                cursor=con.cursor()
                cursor.execute("UPDATE restoranNaplata SET trenutnostanje=%s  WHERE brojračuna=%s",(self.var_condition.get(),self.var_billNo.get()))
                con.commit()
                messagebox.showinfo("OK","Order Success",parent=self.root)
                self.reset()
                self.ShowAllBills()
            except Exception as es:
                messagebox.showwarning("Warning",f"Something went wrong:{es}",parent=self.root)
        

    def deletebill(self):
        if self.var_total.get()!=0:
            messagebox.showerror("Error", "Bill is already charged", parent=self.root)
        else:
            delete=messagebox.askyesno("Restaurant","Do You really want to delete this bill?")
            if delete>0:
                con=Konekcija.getInstance()
                cur=con.cursor()
                cur.execute("DELETE FROM restoranNaplata  WHERE brojračuna=%s",(self.var_billNo.get(),))
                con.commit()
                messagebox.showinfo("OK!","Bill deleted successfully!")
                self.reset()
                self.ShowAllBills()
        

    def charge(self):
        if self.var_condition.get()==0 or self.var_billNo.get()==0:
            messagebox.showerror("Error","Bill does not exist!",parent=self.root)
        elif self.var_total.get()!=0:
            messagebox.showerror("Error", "Bill is already charged", parent=self.root)
        else:
            con=Konekcija.getInstance()
            cursor=con.cursor()
            cursor.execute("UPDATE restoranNaplata SET total=%s,status='naplaćen'  WHERE brojračuna=%s",(self.var_condition.get()+self.var_total.get(),self.var_billNo.get()))
        if self.var_condition.get()>5000:
                cursor.execute("UPDATE gosti SET bodovi=bodovi+200  WHERE idgosti=%s",(self.var_idguest.get(),))
                con.commit()
                messagebox.showinfo("Charge", "Bill charged successfully", parent=self.root)
                self.reset()
                self.ShowAllBills()
        elif self.var_condition.get()>3000 and self.var_condition.get()<=5000:
                cursor.execute("UPDATE gosti SET bodovi=bodovi+100 WHERE idgosti=%s",(self.var_idguest.get(),))
                con.commit()
                messagebox.showinfo("Charge", "Bill charged successfully", parent=self.root)
                self.reset()
                self.ShowAllBills()
        else:
                cursor.execute("UPDATE gosti SET bodovi=bodovi+50  WHERE idgosti=%s",(self.var_idguest.get(),))
                con.commit()
                messagebox.showinfo("Charge", "Bill charged successfully", parent=self.root)
                self.reset()
                self.ShowAllBills()
            
            

    def signingupBill(self):
        if self.var_statusD.get()!="otvoren" :
            messagebox.showerror("Error", "Day is already finished,choose today!", parent=self.root)
        elif self.var_billDay.get()!=self.var_Day.get():
            messagebox.showerror("Error", "This bill is not from this day!", parent=self.root)
        else:
            if self.var_statusR.get()=="naplaćen":
                con=Konekcija.getInstance()
                cur=con.cursor()
                cur.execute("UPDATE pazar SET kasa=%s WHERE dan=%s",(self.var_profit.get()+self.var_total.get(),self.var_Day.get(),))
                cur.execute("UPDATE restoranNaplata SET status='upisan u kasu' WHERE brojračuna=%s",(self.var_billNo.get(),))
                con.commit()
                messagebox.showinfo("OK","Uspešno uvećan pazar",parent=self.root)
                self.reset()
                self.ShowAllBills()
                self.ShowToday()
            elif self.var_statusR.get()=="upisan u kasu":
                messagebox.showerror("Error", "Bill is already signed up!", parent=self.root)
            else:
                messagebox.showerror("Error", "Bill not charged!", parent=self.root)

    def reset(self):
        self.var_quantity1.set(0)
        self.var_quantity2.set(0)
        self.var_quantity3.set(0)
        self.var_quantity4.set(0)
        self.var_quantity5.set(0)
        self.var_quantity6.set(0)
        self.var_quantity7.set(0)
        self.var_quantity8.set(0)
        self.var_quantity9.set(0)
        self.var_quantity10.set(0)
        self.var_quantity11.set(0)
        self.var_quantity12.set(0)
        self.var_quantity13.set(0)
        self.var_quantity14.set(0)
        self.var_quantity15.set(0)
        self.var_quantity16.set(0)
        self.var_quantity17.set(0)
        self.var_quantity18.set(0)
        self.var_quantity19.set(0)
        self.var_quantity20.set(0)
        self.var_quantity21.set(0)
        self.var_quantity22.set(0)
        self.var_quantity23.set(0)
        self.var_quantity24.set(0)
        self.var_quantity25.set(0)
        self.var_quantity26.set(0)
        self.var_price1.set(0)
        self.var_price2.set(0)
        self.var_price3.set(0)
        self.var_price4.set(0)
        self.var_price5.set(0)
        self.var_price6.set(0)
        self.var_price7.set(0)
        self.var_price8.set(0)
        self.var_price9.set(0)
        self.var_price10.set(0)
        self.var_price11.set(0)
        self.var_price12.set(0)
        self.var_price13.set(0)
        self.var_price14.set(0)
        self.var_price15.set(0)
        self.var_price16.set(0)
        self.var_price17.set(0)
        self.var_price18.set(0)
        self.var_price19.set(0)
        self.var_price20.set(0)
        self.var_price21.set(0)
        self.var_price22.set(0)
        self.var_price23.set(0)
        self.var_price24.set(0)
        self.var_price25.set(0)
        self.var_price26.set(0)
        self.var_idA1.set(0)
        self.var_idA2.set(0)
        self.var_idA3.set(0)
        self.var_idA4.set(0)
        self.var_idA5.set(0)
        self.var_idA6.set(0)
        self.var_idA7.set(0)
        self.var_idA8.set(0)
        self.var_idA9.set(0)
        self.var_idA10.set(0)
        self.var_idA11.set(0)
        self.var_idA12.set(0)
        self.var_idA13.set(0)
        self.var_idA14.set(0)
        self.var_idA15.set(0)
        self.var_idA16.set(0)
        self.var_idA17.set(0)
        self.var_idA18.set(0)
        self.var_idA19.set(0)
        self.var_idA20.set(0)
        self.var_idA21.set(0)
        self.var_idA22.set(0)
        self.var_idA23.set(0)
        self.var_idA24.set(0)
        self.var_idA25.set(0)
        self.var_idA26.set(0)
        self.var_KN1.set(0)
        self.var_KN2.set(0)
        self.var_KN3.set(0)
        self.var_KN4.set(0)
        self.var_KN5.set(0)
        self.var_KN6.set(0)
        self.var_KN7.set(0)
        self.var_KN8.set(0)
        self.var_KN9.set(0)
        self.var_KN10.set(0)
        self.var_KN11.set(0)
        self.var_KN12.set(0)
        self.var_KN13.set(0)
        self.var_KN14.set(0)
        self.var_KN15.set(0)
        self.var_KN16.set(0)
        self.var_KN17.set(0)
        self.var_KN18.set(0)
        self.var_KN19.set(0)
        self.var_KN20.set(0)
        self.var_KN21.set(0)
        self.var_KN22.set(0)
        self.var_KN23.set(0)
        self.var_KN24.set(0)
        self.var_KN25.set(0)
        self.var_KN26.set(0)

        self.var_billNo.set(0)
        self.var_idguest.set(0)
        self.var_condition.set(0)
        self.var_total.set(0)
        self.var_statusR.set("otvoren")
        self.var_billDay.set(0)
        self.var_searchBy.set("")
        self.var_searchText.set("")
        if self.var_statusD.get()!="otvoren":
            self.var_Day.set("")
            self.var_profit.set(0)
            self.var_statusD.set("")
        self.var_idnorms.set(0)
        self.var_nameArticle.set("")
        self.var_priceArticle.set(0)
        self.var_quantityArticle.set(0)
        self.var_idArticle.set(0)
        self.var_tour.set(0)
        self.print.delete(*self.print.get_children())
        self.print2.delete(*self.print2.get_children())
        self.print3.delete(*self.print3.get_children())
        self.ShowToday()


    def x3(self):
        self.x=[]
        self.x.extend((self.var_KN1.get(),self.var_KN2.get(),self.var_KN3.get(),self.var_KN4.get(),self.var_KN5.get(),self.var_KN6.get(),self.var_KN7.get(),self.var_KN8.get(),self.var_KN9.get(),self.var_KN10.get(),self.var_KN11.get(),self.var_KN12.get(),self.var_KN13.get(),self.var_KN14.get(),self.var_KN15.get(),self.var_KN16.get(),self.var_KN17.get(),self.var_KN18.get(),self.var_KN19.get(),self.var_KN20.get(),self.var_KN21.get(),self.var_KN22.get(),self.var_KN23.get(),self.var_KN24.get(),self.var_KN25.get(),self.var_KN26.get()))
        self.y=[]
        self.y.extend((self.var_quantity1.get(),self.var_quantity2.get(),self.var_quantity3.get(),self.var_quantity4.get(),self.var_quantity5.get(),self.var_quantity6.get(),self.var_quantity7.get(),self.var_quantity8.get(),self.var_quantity9.get(),self.var_quantity10.get(),self.var_quantity11.get(),self.var_quantity12.get(),self.var_quantity13.get(),self.var_quantity14.get(),self.var_quantity15.get(),self.var_quantity16.get(),self.var_quantity17.get(),self.var_quantity18.get(),self.var_quantity19.get(),self.var_quantity20.get(),self.var_quantity21.get(),self.var_quantity22.get(),self.var_quantity23.get(),self.var_quantity24.get(),self.var_quantity25.get(),self.var_quantity26.get()))
        self.z=[]
        self.z.extend((self.var_idA1.get(),self.var_idA2.get(),self.var_idA3.get(),self.var_idA4.get(),self.var_idA5.get(),self.var_idA6.get(),self.var_idA7.get(),self.var_idA8.get(),self.var_idA9.get(),self.var_idA10.get(),self.var_idA11.get(),self.var_idA12.get(),self.var_idA13.get(),self.var_idA14.get(),self.var_idA15.get(),self.var_idA16.get(),self.var_idA17.get(),self.var_idA18.get(),self.var_idA19.get(),self.var_idA20.get(),self.var_idA21.get(),self.var_idA22.get(),self.var_idA23.get(),self.var_idA24.get(),self.var_idA25.get(),self.var_idA26.get()))

    def itemreduction(self):
        self.x3()
        con=Konekcija.getInstance()
        cursor=con.cursor()
        sql=("UPDATE artikli SET stanjeKgLiKom=stanjeKgLiKom-%s WHERE idartikli=%s")
        for i in range(len(self.x)):
            if i==0:
                value=(self.x[i]*0.01,self.z[i])
                cursor.execute(sql,value)
            elif i==1 or i==2 or i==3 or i==4 or i==7:
                value=(self.x[i]*0.25,self.z[i])
                cursor.execute(sql,value)
            elif i==5:
                value=(self.x[i]*0.2,self.z[i])
                cursor.execute(sql,value)
            elif i==6:
                value=(self.x[i]*0.3,self.z[i])
                cursor.execute(sql,value)
            elif i==8:
                value=(self.x[i]*0.5,self.z[i])
                cursor.execute(sql,value)
            elif i==9:
                value=(self.x[i]*0.15,self.z[i])
                cursor.execute(sql,value)
            elif i==10 or i==11 or i==12:
                value=(self.x[i]*0.03,self.z[i])
                cursor.execute(sql,value)
            elif i==14 or i==16 or i==17:
                value=(self.x[i]*0.2,self.z[i])
                cursor.execute(sql,value)
            elif i==13:
                value=(self.x[i],self.z[i])
                cursor.execute(sql,value)
            else:
                value=(self.x[i]*0.4,self.z[i])
                cursor.execute(sql,value)
        con.commit()

    def limit(self):
        con=Konekcija.getInstance()
        cursor=con.cursor()
        cursor.execute("SELECT * FROM artikli")
        kolone=cursor.fetchall()
        for kolona in kolone :
            if (kolona[2]<kolona[3]):
                messagebox.showinfo("Warning", "Limit,Procurment!!!", parent=self.root)
                messagebox.showinfo("Warning", "Procurment: " +kolona[1], parent=self.root)
                con.commit()

    def off(self):
        con=Konekcija.getInstance()
        messagebox.showinfo("Off","Log-off Succes!")
        con.close()

    def date(self):
        now = strftime("%Y-%m-%d %H:%M:%S")
        self.lbl.config(text = now)
        self.lbl.after(1000, self.date)
    
    def priceProcurment(self):
        self.new_window=Toplevel(self.root)
        self.app=PriceProcurment(self.new_window)

    def closeWindow(self):
            response=messagebox.askyesno('Exit','Do You realy want to exit?',parent=self.root)
            if response:
                self.root.destroy()

'''root=Tk()
object=Restaurant(root)
mainloop()'''